pub enum JobFunction {
    CropTender,
    Shepherd,
    Butcher,
    Fisherman,
    Woodsman,
    HouseCarpenter,
    FishingBoatBuilder,
    WarShipbuilder,
    TraderShipbuilder,
    Quarryman,
    HouseMason,
    FortificationMason,
    Soldier,
    Marine,
    Trader,
}